[package]
name = "humanity"
description = "A small Rust crate to convert numbers, sizes, durations, times, percentages, and permissions into human-readable formats."
version = "0.1.0"
edition = "2024"
