[package]
name = "humaniser"
description = "A small, ergonomic Rust crate to convert numbers, sizes, durations, times, percentages, and permissions into human-readable formats."
version = "0.2.1"
edition = "2024"

[dependencies]
unix_mode = "0.1.4"
