[package]
name = "humanity"
description = "A pure Rust crate to convert numbers, sizes, durations, times, and percentages into human-readable formats."
version = "0.1.0"
edition = "2024"
license = "MIT"